# Generated by Django 5.1.4 on 2025-04-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_bmac_profile_patreon_profile_paypal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bmac',
            new_name='buy_me_a_coffee',
        ),
    ]
