# Generated by Django 5.1.4 on 2025-04-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_bmac_profile_buy_me_a_coffee'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='buy_me_a_coffee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='patreon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='paypal',
            field=models.BooleanField(default=False),
        ),
    ]
