# Generated by Django 5.1.4 on 2025-04-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_buy_me_a_coffee_project_patreon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='core.skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='desired_skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.skill'),
        ),
    ]
