# Generated by Django 5.1.4 on 2025-04-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_skill_profile_skills_project_desired_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Programming Language', 'Programming Language'), ('Framework', 'Framework'), ('Database', 'Database'), ('Technical Tool', 'Technical Tool')], default='Programming Language', max_length=50),
        ),
    ]
