# Generated by Django 5.1.4 on 2025-04-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
    ]
