# Generated by Django 5.1.4 on 2025-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='access_toke',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
