# Generated by Django 5.1.4 on 2025-04-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_access_toke_project_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='access_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='access_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
